"""
Django settings for FLORERIA project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCa2LeZVxu0Gi+R
5tuKP2nDxw8IuUQ4HY4N2iG3Z2i5dUDmQYdHwBzrwcKhUJQQhN88fmKSKqhOtoVk
J0bW7q1umdJ+9p+B/wORmnp7TxKFkXMvVIbjJBncZVcTMRbOhSIb14SMb+4Yr6KY
K5O77ire0eYphHUmLLNDpEjP6UYjf8e3cHhvtMKzZMgFp7LEkA1IBTfzlDwXL6wo
iTrmEtQxFCYFskdCHRvkpd9OZdflZPVoHBwor9vDghQ5Q0QNwVV93m0RetbLDjc3
wIEN4kUQtoqTbHtl2gE3gGU0y09DzBSL9YRevde/TqqYEqEY9iI7AqhAK9o8ujMf
kvH4UNqJAgMBAAECggEAA1VOcHXUUhZtNzgPukRer7jxfSfVzNpwBCLRrnvCoJli
TgKTmasMRFPtr2DHayqdDpWO5CQYbudVbEA/MWG+aH7Vred7rAX0CvaXE9/yH19v
6hEo/Ss6BklFLFPWcJgjkZNcVlSTfMMNHjbz7Wv1TsoYaQThq7JzIm3fJmCYYqu1
KMNR9vQZZ0ZabuARRztBFUiUY47qXbztsYq9H0x+EPqJcsfUAOeZR6P/nXFLDDmG
eNJCJHWtJ6XdHFedYpa6JX2F30yWUiwS550xEPici8jwWJQqWnUEZA1MM2kuSE4X
VjbWDOnQJVkU/2SlLlBEBqufYQYp7ET5lRZA7qZM7QKBgQDRxRHTHPu4VDjk5Chq
dzHEh4sMAmjrHiIe32Vu1ZBhaiQJ6wOX2TVJhtrqJBNm5FQAJLSdgA/qy1vHlpeL
Ddd1Ppb1vgznQbVcpIstEdqG44T5W63EinMXp4BgUfYtZswMwCOQQ9pRZ2VOrOwL
RhTFvOphvmF2p7+YREaXdLDBLQKBgQC8+POWE2z84CVFfPRvTtwG36jSaPiFKUTR
7gMO+PGej3tlfnuNNP0E/yeAz/hBdRlcRZXdhlDNY5KhtF4yRXBvHEVzGAHlx/ie
Yr1wQ2dqoZr5VFLNEGm1D8MAW2QubqXRNf2MK/ib9CfmvirKdKo5tV5yk3m862tp
WeYkAHnATQKBgDdLJg6q9iM5eCHFjm2565FtVRaeT/+h2saehkM34i37Z3KB01mk
dKpj9LKBPegCSa4b/swBZLC0WAX9SQbraB7Ml8hBB2+x31eDO/huW1bxBC0ioGRN
Rlc23N0G3chL739w6i7t489PXOHnLPUvzOvuhy2qnFBFmXhOjvj/VlQlAoGABvF+
wbzk/EWgGPWGZbCYFQiSw2hn+TyS8sO0CRDMj+7lscz77SxNP6nAYdNCY+VRkTpd
T05oGaPW92oRK/exMePwCVKQf0jhsbAfFcjkO97EOvUGNdKsj6KMn66795jJLu60
6jmTYOePr8K8/8NZndU0KzGP/4kG4VAUTK5XyuECgYBoNktwU0b24QuYTf9CEfxf
F4Ewd2YRuOEqKNKW7KnRUqWFLXNNXZw14ucS14HW/1v8Aoh9VvpDNTPDXhSbVTcg
iXUc8AO6kC0AZBvmZoTQRif3f2oTGL7dtYXM3nmqxCx45qSOw2TYxqM/Aecp/ut4
vToFIHwp0hFS+4yEtasGAg==
-----END PRIVATE KEY-----"""

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'users',
    'base',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'django_filters',
    'dynamic_preferences',
    'mozilla_django_oidc',
    'corsheaders',

    'perfiles',
    'catalogo',
    'configuracion',
    'oidc',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'FLORERIA.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

DJANGO_USERS_AUTH_TOKEN = True

USERS_AUTH = {
    "SECRET_KEY": SECRET_KEY,
    "TOKEN_ALGORITHM": "RS256",
    "PUBLIC_KEY": """-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmti3mVcbtBovkebbij9p
w8cPCLlEOB2ODdoht2douXVA5kGHR8Ac68HCoVCUEITfPH5ikiqoTraFZCdG1u6t
bpnSfvafgf8DkZp6e08ShZFzL1SG4yQZ3GVXEzEWzoUiG9eEjG/uGK+imCuTu+4q
3tHmKYR1JiyzQ6RIz+lGI3/Ht3B4b7TCs2TIBaeyxJANSAU385Q8Fy+sKIk65hLU
MRQmBbJHQh0b5KXfTmXX5WT1aBwcKK/bw4IUOUNEDcFVfd5tEXrWyw43N8CBDeJF
ELaKk2x7ZdoBN4BlNMtPQ8wUi/WEXr3Xv06qmBKhGPYiOwKoQCvaPLozH5Lx+FDa
iQIDAQAB
-----END PUBLIC KEY-----"""
}


AUTH_USER_MODEL = 'users.user'

WSGI_APPLICATION = 'FLORERIA.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'es-mx'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

APPEND_SLASH = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


DYNAMIC_PREFERENCES = {
    "ENABLE_CACHE": False,  # en desarrollo, podés desactivarlo para ver los cambios al instante
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=int(os.getenv('SIMPLE_JWT_TOKEN_LIFETIME', 30))),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=int(os.getenv('SIMPLE_JWT_REFRESH_LIFETIME', 30))),
    'ROTATE_REFRESH_TOKENS': os.getenv('ROTATE_REFRESH_TOKENS', True),
    'BLACKLIST_AFTER_ROTATION': os.getenv('BLACKLIST_AFTER_ROTATION', True),
    'UPDATE_LAST_LOGIN': os.getenv('UPDATE_LAST_LOGIN', False),
    'ALGORITHM': os.getenv('ALGORITHM', 'RS256'),
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'VERIFYING_KEY': """-----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmti3mVcbtBovkebbij9p
    w8cPCLlEOB2ODdoht2douXVA5kGHR8Ac68HCoVCUEITfPH5ikiqoTraFZCdG1u6t
    bpnSfvafgf8DkZp6e08ShZFzL1SG4yQZ3GVXEzEWzoUiG9eEjG/uGK+imCuTu+4q
    3tHmKYR1JiyzQ6RIz+lGI3/Ht3B4b7TCs2TIBaeyxJANSAU385Q8Fy+sKIk65hLU
    MRQmBbJHQh0b5KXfTmXX5WT1aBwcKK/bw4IUOUNEDcFVfd5tEXrWyw43N8CBDeJF
    ELaKk2x7ZdoBN4BlNMtPQ8wUi/WEXr3Xv06qmBKhGPYiOwKoQCvaPLozH5Lx+FDa
    iQIDAQAB
    -----END PUBLIC KEY-----"""
}

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'base.managers.CustomPagination',
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated'
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'users.managers.CustomJWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ),
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend'
    ],
    'DEFAULT_PARSER_CLASSES': (
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.MultiPartParser',
        'rest_framework.parsers.FormParser',
    ),
}

# CONFIGURACION DE AUTENTICACION

AUTHENTICATION_BACKENDS = (
    'oidc.backends.CustomOIDCAuthenticationBackend',
    'django.contrib.auth.backends.ModelBackend',
)

# CONFIGURACION DE OIDC DE KEYCLOAK

OIDC_OP_BASE_URL = 'https://keycloak-demo.apismty.gob.mx/realms/floreria_app'

OIDC_OP_AUTHORIZATION_ENDPOINT = f'{OIDC_OP_BASE_URL}/protocol/openid-connect/auth'
OIDC_OP_TOKEN_ENDPOINT = f'{OIDC_OP_BASE_URL}/protocol/openid-connect/token'
OIDC_OP_USER_ENDPOINT = f'{OIDC_OP_BASE_URL}/protocol/openid-connect/userinfo'
OIDC_OP_JWKS_ENDPOINT = f'{OIDC_OP_BASE_URL}/protocol/openid-connect/certs'

OIDC_RP_CLIENT_ID = 'floreria_app'
OIDC_RP_CLIENT_SECRET = 'Notu2p9zBUzu4UZcVBmHVW5hoGcvwQgQ'
OIDC_RP_SCOPES = 'openid profile email'

LOGIN_URL = '/oidc/authenticate/'
OIDC_RP_SIGN_ALGO = 'RS256'
LOGOUT_REDIRECT_URL = '/'
LOGIN_REDIRECT_URL = 'http://localhost:3000/'

# Opcional: auto-crear usuarios
OIDC_CREATE_USER = True

# Almacenar tokens en la sesión
OIDC_STORE_ACCESS_TOKEN = True
OIDC_STORE_ID_TOKEN = True

# CONFIGURACION DE CORS
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # Tu frontend React
]
